### ISSUE TITLE
为团队起个响亮的名字吧！还有你的个人介绍！

### ISSUE THREAD

**Issue by sumin1123** [sumin1123/Bookcrossing#1]
@justin007755 @Leon-Huang @thxiami @dragon86yq @pengbo0530

Hello all,
- 请为咱们的团队起个响亮的名字吧！有什么好主意，请在下面留言。
- 请在issue下面留下你的个人介绍，我已经起了个头，让其他同学、教练认识你一下。
- 另外，关于项目的名字，提交项目的时候我先随便起了一个，叫Bookcrossing。有其他想法的，也请留下你的建议。

BR

**Comment by sumin1123** [comment]
姓名：苏敏
名号：喵酱
GitHub Username：sumin1123
坐标：北京
个人简介：电力行业项目经理，供电方向，编程初次接触。
团队名称建议：？？？
![](https://github.com/sumin1123/Git_Github_Learning/blob/master/IMG_2700.JPG?raw=true)

**Comment by thxiami** [comment]
- 姓名：李奕威
- 名号：虾米
- GitHub Username：thxiami
- 坐标：重庆
- 个人简介：土木研究生在读，接触python半年有余，准备转行作后端开发。
- 团队名称：漂书 （想到这个名字后百度了一下，发现还有同名类似产品）
- 照片：
    <img src="https://user-images.githubusercontent.com/26535231/31162191-821f954a-a8a1-11e7-900f-c6d8f1e38473.png" width="50%" height="50%">

**Comment by dragon86yq** [comment]
- 姓名：李斯龙
- 名号：木子
- GitHub Username：dragon86yq
坐标：武汉
个人简介：通信研发人员， 通过大数据接触Python，接触python不到1年
团队名称建议：书源（书指图书，源有两层含义第一层表示起源，第二层取自三点水，表示漂流）
- 照片：人丑，就不po照了

**Comment by Leon-Huang** [comment]
back to 帝都了
姓名：黄鹄
名号：黄老邪
GitHub Username：Leon-Huang
坐标：帝都
个人简介：python小白，啥都懂一点皮毛
照片：人丑，就不po照了

**Comment by justin007755** [comment]
- 姓名：张旭
- 名号：Justin
- GitHub Username：justin007755
- 坐标：北京
- 个人简介：网络工程师
各种技术都了解一点，都不精通。Python接触了很久，但使用的不太多。
