### ISSUE TITLE
CSS制作响应页面，在手机端不能按照预想匹配

### ISSUE THREAD

**Issue by sumin1123** [sumin1123/Bookcrossing#11]
* 我在CSS里设置如下：
    * 屏幕像素>960px，在浏览器效果如下：
![960](https://user-images.githubusercontent.com/26780720/31580893-01c5dc00-b18f-11e7-8042-8b49e02cdfe9.png)
    * 600px<屏幕像素<960px，在浏览器效果如下：
![600960](https://user-images.githubusercontent.com/26780720/31580926-da4f9962-b18f-11e7-9dc8-c11b4e0f630b.png)
    * 屏幕像素<600px，在浏览器效果如下：
![600](https://user-images.githubusercontent.com/26780720/31580945-28868ac8-b190-11e7-8a7b-56fb5a4fed12.png)

* 但是是换做手机浏览时发现：
    * iphone 6S 分辨率1334x750像素；
    * 750像素介于600和960px之间，但是实际按照`<600px`的样式显示；使用Chrome开发者模式，也是显示`<600px`样式。
![default](https://user-images.githubusercontent.com/26780720/31581029-99354f8c-b192-11e7-98df-49e151206010.png)

* 我的问题是：不知道为什么有这样的差异？源文件如下：
[html](https://github.com/sumin1123/Bookcrossing/blob/master/index01.html)
[CSS](https://github.com/sumin1123/Bookcrossing/blob/master/style01.css)

**Comment by thxiami** [comment]
@sumin1123 我记得李炜枫教练说过可以通过 js 来调整页面, 适应不同屏幕尺寸。如果css的路暂时没走通的话， 可以基于此搜索下是否有框架可以实现。

**Comment by sumin1123** [comment]
@thxiami 
谢谢，我可以用bootstrap解决，目前CSS这里不清楚到底为什么，始终是个心结😺

**Comment by sumin1123** [comment]
* from 大猫教练的回复：https://www.paintcodeapp.com/news/ultimate-guide-to-iphone-resolutions

* 说明：
    * 由于从iphone 3 到 4，屏幕横向的像素从320增至640。同样10*10像素的方框，在iphone3里显示合适，但到iphone4就会很小。所以iphone4后的手机都设置了一个放大比例，每个厂家设置不同。例如，iphone是2，也就是10*10的像素在iphone3显示10*10，到了iphone4就变为20*20。
