### ISSUE TITLE
[On Line Meet Up]第一次聚会时间征询？

### ISSUE THREAD

**Issue by sumin1123** [sumin1123/Bookcrossing#3]
Hello all

- 第一次线上讨论，想和大家约个时间，**请大家回复自己方便的时间**。
- 沟通方式，我能提供：
    - Webex网络会议，用来共享屏幕
    - 全时电话会议中心，用来多方通话。大家拨通后，可以让会议助理打回到自己的电话上。
    - 大家还有其他聚会方式推荐吗？可以留言。
- 第一次线上讨论，议题：
    - 功能分析问题
    - 分工
    - 后续项目开展方式.

**Comment by sumin1123** [comment]
第一次沟通时间，我随时可以，我觉得越早越好。
---
后面整个十月，我自己的时间安排如下：
- **十一假期**
    - 公司休假到10月8号，5号需要加班写一天报告，但是是在家加班，时间也灵活。
    - 9号前，全天可用。
- **工作日**，10月9号开始上班了
    - 早6-早7，可以用来研究大作业。
    - 午12-午1，公司午休时间，可用。
    - 晚7-晚11，晚饭+跑步，其余时间可用。
- **周六日**，离路演还有6个周末
    - 除了去老妈家+锻炼，基本全天可用。

**Comment by thxiami** [comment]
- 第一次线上讨论时间：
    - 10.8晚上导师组织开会，其余时间均可以讨论。**我也觉得越早越好，尽量本周可以出一个mvp，以周为单位迭代产品**。
- 沟通方式补充：
    - 可以借开智账号，通过Zoom.us讨论，也可以分享屏幕
- 第一次线上讨论，议题补充：
    - 估计功能开发耗时，重要程度，排出优先级
    - 会议记录人员（轮流，或固定人员，可招募观察员）
    - 沟通讨论后，进度如何控制管理
- 时间安排
    - **十一假期**
        - 8号前，全天可用
    - **工作日**
        - 准备十一后找实习，若有实习则下班后可用于大作业，预计晚8-11；无实习则全天可以
        - 导师安排有科研任务，但不定时，有任务时可能需要1-2个晚上来完成
    - **周六日**
        - 周六 可用
        - 周日 
            - 上午：可用
            - 下午：准备工作汇报
            - 晚上：8-11 导师开会

**Comment by thxiami** [comment]
@sumin1123 
- 第一次线上讨论时间：
    - 10.8晚上导师组织开会，其余时间均可以讨论。**我也觉得越早越好，尽量本周可以出一个mvp，以周为单位迭代产品**。
- 沟通方式补充：
    - 可以借开智账号，通过Zoom.us讨论，也可以分享屏幕
- 第一次线上讨论，议题补充：
    - 估计功能开发耗时，重要程度，排出优先级
    - 会议记录人员（轮流，或固定人员，可招募观察员）
    - 沟通讨论后，进度如何控制管理
- 时间安排
    - **十一假期**
        - 8号前，全天可用
    - **工作日**
        - 准备十一后找实习，若有实习则下班后可用于大作业，预计晚8-11；无实习则全天可以
        - 导师安排有科研任务，但不定时，有任务时可能需要1-2个晚上来完成
    - **周六日**
        - 周六 可用
        - 周日 
            - 上午：可用
            - 下午：准备工作汇报
            - 晚上：8-11 导师开会

**Comment by justin007755** [comment]
这个安排很不错，软件开发最好是小组成员都在同一个办公室，效率比较高。但实际情况不可能，所以电话会议是一种不错的方式。

- 工作日

    一般早晨5:30起床，先看公司的邮件，然后有一点时间可以用来研究大作业。
    白天可以抽出个吧小时来研究，但不是每天都有时间。
    晚上基本都是公司的会议和小孩的作业，如果咱们要开线上会议，最好安排在周四周五晚上。

- 周六日，主要负责小孩的各种课程，间歇有几个小时可以利用。。。：（

建议先尽快来一次试一试。。。。
